name: sqfentity_example
description: Sqlite3Entity ORM for Flutter/Dart lets you build and execute SQL commands easily and quickly with the help of fluent methods similar to .Net Entity Framework.
homepage: https://github.com/hhtokpinar/sqfEntity

version: 1.3.0
publish_to: none

environment:
  sdk: ">=2.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.17.0"
  http: ^0.13.4
  flutter_datetime_picker_plus: ^2.0.1
  #flutter_datetime_picker:
  # git:
  #   url: https://github.com/Realank/flutter_datetime_picker.git

  sqflite_sqlcipher: any
  #meta: ^1.7.0
  sqlite3_entity:
    path: ../sqlite3_entity
  sqlite3_entity_gen:
    path: ../sqlite3_entity_gen

dev_dependencies:
  build_runner: ^2.1.11
  build_verify: ^3.0.0
  sqflite_common_ffi:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/chinook.sqlite
    - assets/line.png
    - assets/windows-wallpaper.jpg
    - assets/no-picture.png

  fonts:
    - family: LexendDeca
      fonts:
        - asset: fonts/LexendDeca-Regular.ttf
          style: normal

    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Thin.ttf
          style: normal
